// Generated by jextract

package com.github.extism;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2 {

    static final FunctionDescriptor extism_log_file$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle extism_log_file$MH = RuntimeHelper.downcallHandle(
        "extism_log_file",
        constants$2.extism_log_file$FUNC, false
    );
    static final FunctionDescriptor extism_version$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle extism_version$MH = RuntimeHelper.downcallHandle(
        "extism_version",
        constants$2.extism_version$FUNC, false
    );
}


