// Generated by jextract

package com.github.extism;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1 {

    static final FunctionDescriptor extism_plugin_config$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle extism_plugin_config$MH = RuntimeHelper.downcallHandle(
        "extism_plugin_config",
        constants$1.extism_plugin_config$FUNC, false
    );
    static final FunctionDescriptor extism_plugin_function_exists$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle extism_plugin_function_exists$MH = RuntimeHelper.downcallHandle(
        "extism_plugin_function_exists",
        constants$1.extism_plugin_function_exists$FUNC, false
    );
    static final FunctionDescriptor extism_plugin_call$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle extism_plugin_call$MH = RuntimeHelper.downcallHandle(
        "extism_plugin_call",
        constants$1.extism_plugin_call$FUNC, false
    );
    static final FunctionDescriptor extism_error$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle extism_error$MH = RuntimeHelper.downcallHandle(
        "extism_error",
        constants$1.extism_error$FUNC, false
    );
    static final FunctionDescriptor extism_plugin_output_length$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle extism_plugin_output_length$MH = RuntimeHelper.downcallHandle(
        "extism_plugin_output_length",
        constants$1.extism_plugin_output_length$FUNC, false
    );
    static final FunctionDescriptor extism_plugin_output_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle extism_plugin_output_data$MH = RuntimeHelper.downcallHandle(
        "extism_plugin_output_data",
        constants$1.extism_plugin_output_data$FUNC, false
    );
}


