// Generated by jextract

package com.github.extism;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor extism_context_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle extism_context_new$MH = RuntimeHelper.downcallHandle(
        "extism_context_new",
        constants$0.extism_context_new$FUNC, false
    );
    static final FunctionDescriptor extism_context_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle extism_context_free$MH = RuntimeHelper.downcallHandle(
        "extism_context_free",
        constants$0.extism_context_free$FUNC, false
    );
    static final FunctionDescriptor extism_plugin_new$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_BOOL$LAYOUT
    );
    static final MethodHandle extism_plugin_new$MH = RuntimeHelper.downcallHandle(
        "extism_plugin_new",
        constants$0.extism_plugin_new$FUNC, false
    );
    static final FunctionDescriptor extism_plugin_update$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_BOOL$LAYOUT
    );
    static final MethodHandle extism_plugin_update$MH = RuntimeHelper.downcallHandle(
        "extism_plugin_update",
        constants$0.extism_plugin_update$FUNC, false
    );
    static final FunctionDescriptor extism_plugin_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle extism_plugin_free$MH = RuntimeHelper.downcallHandle(
        "extism_plugin_free",
        constants$0.extism_plugin_free$FUNC, false
    );
    static final FunctionDescriptor extism_context_reset$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle extism_context_reset$MH = RuntimeHelper.downcallHandle(
        "extism_context_reset",
        constants$0.extism_context_reset$FUNC, false
    );
}


